apiVersion: v1
kind: Service
metadata:
  name: nginx-sample-service
  namespace: default
spec:
  selector:
    app: nginx-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
